import error 
print(error.mi_funcion)